# coding: utf-8

# flake8: noqa
"""
    MELI Markeplace SDK

    This is a the codebase to generate a SDK for Open Platform Marketplace  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from .attributes import Attributes
from .attributes_value_struct import AttributesValueStruct
from .attributes_values import AttributesValues
from .inline_object import InlineObject
from .item import Item
from .item_pictures import ItemPictures
from .variations import Variations
from .variations_attribute_combinations import VariationsAttributeCombinations
